/* tslint:disable */
/* eslint-disable */
/**
 * Timetable API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RailwayStation,
    RailwayStationFromJSON,
    RailwayStationFromJSONTyped,
    RailwayStationToJSON,
} from './';

/**
 * 
 * @export
 * @interface RailwayStationConnectionDto
 */
export interface RailwayStationConnectionDto {
    /**
     * 
     * @type {RailwayStation}
     * @memberof RailwayStationConnectionDto
     */
    arrivalStation?: RailwayStation;
    /**
     * 
     * @type {object}
     * @memberof RailwayStationConnectionDto
     */
    arrivalTime?: object;
    /**
     * 
     * @type {Date}
     * @memberof RailwayStationConnectionDto
     */
    date?: Date;
    /**
     * 
     * @type {RailwayStation}
     * @memberof RailwayStationConnectionDto
     */
    departureStation?: RailwayStation;
    /**
     * 
     * @type {object}
     * @memberof RailwayStationConnectionDto
     */
    departureTime?: object;
}

export function RailwayStationConnectionDtoFromJSON(json: any): RailwayStationConnectionDto {
    return RailwayStationConnectionDtoFromJSONTyped(json, false);
}

export function RailwayStationConnectionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RailwayStationConnectionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'arrivalStation': !exists(json, 'arrivalStation') ? undefined : RailwayStationFromJSON(json['arrivalStation']),
        'arrivalTime': !exists(json, 'arrivalTime') ? undefined : json['arrivalTime'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'departureStation': !exists(json, 'departureStation') ? undefined : RailwayStationFromJSON(json['departureStation']),
        'departureTime': !exists(json, 'departureTime') ? undefined : json['departureTime'],
    };
}

export function RailwayStationConnectionDtoToJSON(value?: RailwayStationConnectionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'arrivalStation': RailwayStationToJSON(value.arrivalStation),
        'arrivalTime': value.arrivalTime,
        'date': value.date === undefined ? undefined : (value.date.toISOString().substr(0,10)),
        'departureStation': RailwayStationToJSON(value.departureStation),
        'departureTime': value.departureTime,
    };
}


