/* tslint:disable */
/* eslint-disable */
/**
 * Timetable API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TrainCarDto,
    TrainCarDtoFromJSON,
    TrainCarDtoFromJSONTyped,
    TrainCarDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface ReservationDto
 */
export interface ReservationDto {
    /**
     * 
     * @type {number}
     * @memberof ReservationDto
     */
    id?: number;
    /**
     * 
     * @type {TrainCarDto}
     * @memberof ReservationDto
     */
    trainCar?: TrainCarDto;
}

export function ReservationDtoFromJSON(json: any): ReservationDto {
    return ReservationDtoFromJSONTyped(json, false);
}

export function ReservationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'trainCar': !exists(json, 'trainCar') ? undefined : TrainCarDtoFromJSON(json['trainCar']),
    };
}

export function ReservationDtoToJSON(value?: ReservationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'trainCar': TrainCarDtoToJSON(value.trainCar),
    };
}


