/* tslint:disable */
/* eslint-disable */
/**
 * Timetable API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: lukas.schoerghuber@posteo.at
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RailwayStationDto,
    RailwayStationDtoFromJSON,
    RailwayStationDtoFromJSONTyped,
    RailwayStationDtoToJSON,
    TrainConnectionDto,
    TrainConnectionDtoFromJSON,
    TrainConnectionDtoFromJSONTyped,
    TrainConnectionDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface RailwayStationConnectionDto
 */
export interface RailwayStationConnectionDto {
    /**
     * 
     * @type {RailwayStationDto}
     * @memberof RailwayStationConnectionDto
     */
    arrivalStation?: RailwayStationDto;
    /**
     * 
     * @type {string}
     * @memberof RailwayStationConnectionDto
     */
    arrivalTime?: string;
    /**
     * 
     * @type {RailwayStationDto}
     * @memberof RailwayStationConnectionDto
     */
    departureStation?: RailwayStationDto;
    /**
     * 
     * @type {string}
     * @memberof RailwayStationConnectionDto
     */
    departureTime?: string;
    /**
     * 
     * @type {TrainConnectionDto}
     * @memberof RailwayStationConnectionDto
     */
    trainConnection?: TrainConnectionDto;
}

export function RailwayStationConnectionDtoFromJSON(json: any): RailwayStationConnectionDto {
    return RailwayStationConnectionDtoFromJSONTyped(json, false);
}

export function RailwayStationConnectionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RailwayStationConnectionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'arrivalStation': !exists(json, 'arrivalStation') ? undefined : RailwayStationDtoFromJSON(json['arrivalStation']),
        'arrivalTime': !exists(json, 'arrivalTime') ? undefined : json['arrivalTime'],
        'departureStation': !exists(json, 'departureStation') ? undefined : RailwayStationDtoFromJSON(json['departureStation']),
        'departureTime': !exists(json, 'departureTime') ? undefined : json['departureTime'],
        'trainConnection': !exists(json, 'trainConnection') ? undefined : TrainConnectionDtoFromJSON(json['trainConnection']),
    };
}

export function RailwayStationConnectionDtoToJSON(value?: RailwayStationConnectionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'arrivalStation': RailwayStationDtoToJSON(value.arrivalStation),
        'arrivalTime': value.arrivalTime,
        'departureStation': RailwayStationDtoToJSON(value.departureStation),
        'departureTime': value.departureTime,
        'trainConnection': TrainConnectionDtoToJSON(value.trainConnection),
    };
}


