/* tslint:disable */
/* eslint-disable */
/**
 * Timetable API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: lukas.schoerghuber@posteo.at
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum TrainCarType {
    COUCHETTE = 'COUCHETTE',
    SEAT = 'SEAT',
    SLEEPER = 'SLEEPER'
}

export function TrainCarTypeFromJSON(json: any): TrainCarType {
    return TrainCarTypeFromJSONTyped(json, false);
}

export function TrainCarTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainCarType {
    return json as TrainCarType;
}

export function TrainCarTypeToJSON(value?: TrainCarType | null): any {
    return value as any;
}

