/* tslint:disable */
/* eslint-disable */
/**
 * Timetable API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: lukas.schoerghuber@posteo.at
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TrainCarDto,
    TrainCarDtoFromJSON,
    TrainCarDtoFromJSONTyped,
    TrainCarDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface TrainConnectionDto
 */
export interface TrainConnectionDto {
    /**
     * 
     * @type {string}
     * @memberof TrainConnectionDto
     */
    code: string;
    /**
     * 
     * @type {number}
     * @memberof TrainConnectionDto
     */
    id: number;
    /**
     * 
     * @type {Array<TrainCarDto>}
     * @memberof TrainConnectionDto
     */
    trainCars?: Array<TrainCarDto>;
}

export function TrainConnectionDtoFromJSON(json: any): TrainConnectionDto {
    return TrainConnectionDtoFromJSONTyped(json, false);
}

export function TrainConnectionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainConnectionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'id': json['id'],
        'trainCars': !exists(json, 'trainCars') ? undefined : ((json['trainCars'] as Array<any>).map(TrainCarDtoFromJSON)),
    };
}

export function TrainConnectionDtoToJSON(value?: TrainConnectionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'id': value.id,
        'trainCars': value.trainCars === undefined ? undefined : ((value.trainCars as Array<any>).map(TrainCarDtoToJSON)),
    };
}


