/* tslint:disable */
/* eslint-disable */
/**
 * Timetable API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: lukas.schoerghuber@posteo.at
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TrainCarType,
    TrainCarTypeFromJSON,
    TrainCarTypeFromJSONTyped,
    TrainCarTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface TrainCarDto
 */
export interface TrainCarDto {
    /**
     * 
     * @type {number}
     * @memberof TrainCarDto
     */
    capacity: number;
    /**
     * 
     * @type {number}
     * @memberof TrainCarDto
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof TrainCarDto
     */
    number: number;
    /**
     * 
     * @type {TrainCarType}
     * @memberof TrainCarDto
     */
    type: TrainCarType;
}

export function TrainCarDtoFromJSON(json: any): TrainCarDto {
    return TrainCarDtoFromJSONTyped(json, false);
}

export function TrainCarDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainCarDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'capacity': json['capacity'],
        'id': json['id'],
        'number': json['number'],
        'type': TrainCarTypeFromJSON(json['type']),
    };
}

export function TrainCarDtoToJSON(value?: TrainCarDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'capacity': value.capacity,
        'id': value.id,
        'number': value.number,
        'type': TrainCarTypeToJSON(value.type),
    };
}


